**This notebook is an exercise in the [SQL](https://www.kaggle.com/learn/intro-to-sql) course.  You can reference the tutorial at [this link](https://www.kaggle.com/dansbecker/group-by-having-count).**

---

# Introduction

Queries with **GROUP BY** can be powerful. There are many small things that can trip you up (like the order of the clauses), but it will start to feel natural once you've done it a few times. Here, you'll write queries using **GROUP BY** to answer questions from the Hacker News dataset.

Before you get started, run the following cell to set everything up:

In [4]:
# Set up feedback system
from learntools.core import binder
binder.bind(globals())
from learntools.sql.ex3 import *
print("Setup Complete")

Setup Complete

The code cell below fetches the `full` table from the `hacker_news` dataset.  We also preview the first five rows of the table.

In [5]:
from google.cloud import bigquery

# Create a "Client" object
client = bigquery.Client()

# Construct a reference to the "hacker_news" dataset
dataset_ref = client.dataset("hacker_news", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

# Construct a reference to the "full" table
table_ref = dataset_ref.table("full")

# API request - fetch the table
table = client.get_table(table_ref)

# Preview the first five lines of the table
client.list_rows(table, max_results=5).to_dataframe()

Using Kaggle's public dataset BigQuery integration.

,title,url,text,dead,by,score,time,timestamp,type,id,parent,descendants,ranking,deleted
0,None,None,"If the crocodile looked him up on Google, we b...",None,raxxorrax,NaN,1633421535,2021-10-05 08:12:15+00:00,comment,28756662,28750122,NaN,NaN,None
1,None,None,What exactly are you looking for? I think Pyto...,None,abiro,NaN,1569141387,2019-09-22 08:36:27+00:00,comment,21040311,21040141,NaN,NaN,None
2,None,None,"Ironically, this very project might help out w...",None,mjevans,NaN,1505769703,2017-09-18 21:21:43+00:00,comment,15279716,15276626,NaN,NaN,None
3,None,None,As you start to gain some experience it can be...,None,every_other,NaN,1538575027,2018-10-03 13:57:07+00:00,comment,18130207,18128477,NaN,NaN,None
4,None,None,"That’s what I was referring to, yes. I heard o...",None,manmal,NaN,1615664155,2021-03-13 19:35:55+00:00,comment,26449260,26449237,NaN,NaN,None

# Exercises

### 1) Prolific commenters

Hacker News would like to send awards to everyone who has written more than 10,000 posts. Write a query that returns all authors with more than 10,000 posts as well as their post counts. Call the column with post counts `NumPosts`.

In case sample query is helpful, here is a query you saw in the tutorial to answer a similar question:
```
query = """
        SELECT parent, COUNT(1) AS NumPosts
        FROM `bigquery-public-data.hacker_news.full`
        GROUP BY parent
        HAVING COUNT(1) > 10
        """
```

In [8]:
# Query to select prolific commenters and post counts
prolific_commenters_query = """
                            SELECT `by` AS author, COUNT(1) AS NumPosts
                            FROM `bigquery-public-data.hacker_news.full`
                            GROUP BY `by`
                            HAVING COUNT(1) > 10000
                            """ # Your code goes here

# Set up the query (cancel the query if it would use too much of 
# your quota, with the limit set to 1 GB)
safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=10**10)
query_job = client.query(prolific_commenters_query, job_config=safe_config)

# API request - run the query, and return a pandas DataFrame
prolific_commenters = query_job.to_dataframe()

# View top few rows of results
print(prolific_commenters.head())

# Check your answer
q_1.check()

         author  NumPosts
0      jacquesm     45023
1   userbinator     12662
2        davidw     13894
3  thaumasiotes     11712
4         gaius     12729

Correct

For the solution, uncomment the line below.

In [9]:
q_1.solution()

Solution:
```python

prolific_commenters_query = """
                            SELECT `by` AS author, COUNT(1) AS NumPosts
                            FROM `bigquery-public-data.hacker_news.full`
                            GROUP BY author
                            HAVING COUNT(1) > 10000
                            """

```

### 2) Deleted comments

How many comments have been deleted? (If a comment was deleted, the `deleted` column in the table will have the value `True`.)

In [11]:
# Write your query here and figure out the answer
del_comments_query = """
                     SELECT COUNT(id) AS DelComments
                     FROM `bigquery-public-data.hacker_news.full`
                     WHERE deleted = True
                     """

# Set up the query (cancel the query if it would use too much of 
# your quota, with the limit set to 1 GB)
safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=10**10)
query_job = client.query(del_comments_query, job_config=safe_config)

# API request - run the query, and return a pandas DataFrame
del_comments = query_job.to_dataframe()

# View top few rows of results
print(del_comments.head())

   DelComments
0       859401

In [12]:
num_deleted_posts = 859401 # Put your answer here

# Check your answer
q_2.check()

Correct

For the solution, uncomment the line below.

In [13]:
q_2.solution()

Solution:
```python

# Query to determine how many posts were deleted
deleted_posts_query = """
                      SELECT COUNT(1) AS num_deleted_posts
                      FROM `bigquery-public-data.hacker_news.full`
                      WHERE deleted = True
                      """

# Set up the query
query_job = client.query(deleted_posts_query)

# API request - run the query, and return a pandas DataFrame
deleted_posts = query_job.to_dataframe()

# View results
print(deleted_posts)

num_deleted_posts = 859401

```

# Keep Going
**[Click here](https://www.kaggle.com/dansbecker/order-by)** to move on and learn about the **ORDER BY** clause.

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/intro-to-sql/discussion) to chat with other learners.*